from datetime import datetime

from utils.chat_utils import get_chat_statistics

from config import MODEL_NAME, APP_VERSION, AUTHOR



# Export conversation history as a formatted text string

def export_as_text(
        history: list[dict],
        metadata: dict,
    ) -> str:

    stats = get_chat_statistics(history)

    lines = [
        "=" * 50,
        "Memory ChatBot AI",
        "Conversation Export",
        "=" * 50,
        "",
        f"Conversation ID   : {metadata['conversation_id']}",
        f"Exported On       : {metadata['exported_on']}",
        f"Messages          : {stats['message_count']}",
        f"User Messages     : {stats['user_messages']}",
        f"Assistant Messages: {stats['assistant_messages']}",
        f"Duration          : {stats['session_duration']}",
        "",
        "=" * 50,
        "",
    ]
    for message in history:

        speaker = "👤 User" if message["role"] == "user" else "🤖 Assistant"
        timestamp = message.get("timestamp", "Unknown Time")


        lines.extend(
        [
            "-" * 50,
            f"{speaker}",
            f"🕒 {timestamp}",
            "",
            message["content"],
            "",
        ]
)
    return "\n".join(lines)



# Export conversation history as a formatted Markdown string

def export_as_markdown(
        history: list[dict],
        metadata: dict,
    ) -> str:

    stats = get_chat_statistics(history)

    lines = [
        "# 🧠 Memory ChatBot AI",
        "",
        "## Conversation Export",
        "",
        "Generated by **Memory ChatBot AI v2.0**",
        "",

        "```text",
        f"Conversation ID   : {metadata['conversation_id']}",
        f"Exported On       : {metadata['exported_on']}",
        f"Model             : {MODEL_NAME}",
        f"Version           : v{APP_VERSION}",

        "```",

        "",

        "## 📊 Conversation Statistics",
        "",

        "| Metric              | Value |",
        "|---------------------|------:|",
        f"| Messages            | {stats['message_count']:>5} |",
        f"| User Messages       | {stats['user_messages']:>5} |",
        f"| Assistant Messages  | {stats['assistant_messages']:>5} |",
        f"| Duration            | {stats['session_duration']:>5} |",

        "",

        "---",

        "",
    ]

    for message in history:
    
        speaker = "👤 User" if message["role"] == "user" else "🤖 Assistant"

        timestamp = message.get("timestamp", "Unknown Time")

        lines.extend(
            [
                f"### {speaker}",
                "",
                f"🕒 **Time:** {timestamp}",
                "",
                message["content"],
                "",
                "---",
                "",
            ]
        )


    lines.extend(
    [
        "",
        "---",
        "",
        f"Generated with **Memory ChatBot AI v{APP_VERSION}**",
        "",
        f"Built by **{AUTHOR}**"
    ]
)

    return "\n".join(lines)
            