# Standard Library
from io import BytesIO


# Third-Party Library
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Table,
    TableStyle,
    Spacer,
    HRFlowable,
)

from reportlab.lib.styles import getSampleStyleSheet

from reportlab.lib import colors


# Local Library
from config import MODEL_NAME, APP_VERSION, AUTHOR

from utils.chat_utils import get_chat_statistics

from models import (
    ChatMessage,
    ConversationMetadata,
    ChatStatistics,
)


# Create the metadata table displayed at the top of the PDF.
def _create_metadata_table(
    metadata: ConversationMetadata,
) -> Table:
    """
    Create the metadata table displayed
    at the top of the PDF.
    """

    metadata_table_data = [
        ["Conversation ID", metadata["conversation_id"]],
        ["Exported On", metadata["exported_on"]],
        ["Model", MODEL_NAME],
        ["Version", f"v{APP_VERSION}"],
    ]

    metadata_table = Table(
        metadata_table_data,
        colWidths=[140, 260],
    )

    metadata_table.setStyle(
        TableStyle(
            [
                ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                ("FONTNAME", (1, 0), (1, -1), "Helvetica"),
                ("FONTSIZE", (0, 0), (-1, -1), 10),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("ALIGN", (0, 0), (0, -1), "LEFT"),
                ("ALIGN", (1, 0), (1, -1), "LEFT"),
            ]
        )
    )

    metadata_table.hAlign = "LEFT"

    return metadata_table


# Create the conversation statistics table.
def _create_statistics_table(
    stats: ChatStatistics,
) -> Table:
    """
    Create the conversation statistics table.
    """

    table_data = [
        ["Metric", "Value"],
        ["Messages", str(stats["message_count"])],
        ["User Messages", str(stats["user_messages"])],
        ["Assistant Messages", str(stats["assistant_messages"])],
        ["Duration", stats["session_duration"]],
    ]

    stats_table = Table(
        table_data,
        colWidths=[220, 100],
    )

    stats_table.setStyle(
        TableStyle(
            [
                # Header
                ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.black),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, 0), 11),
                ("BOTTOMPADDING", (0, 0), (-1, 0), 10),

                # Row Backgrounds
                ("BACKGROUND", (0, 1), (-1, 1), colors.white),
                ("BACKGROUND", (0, 2), (-1, 2), colors.whitesmoke),
                ("BACKGROUND", (0, 3), (-1, 3), colors.white),
                ("BACKGROUND", (0, 4), (-1, 4), colors.whitesmoke),

                # Body
                ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
                ("FONTSIZE", (0, 1), (-1, -1), 10),
                ("TOPPADDING", (0, 1), (-1, -1), 8),
                ("BOTTOMPADDING", (0, 1), (-1, -1), 8),

                # Alignment
                ("ALIGN", (0, 0), (0, -1), "LEFT"),
                ("ALIGN", (1, 0), (1, -1), "CENTER"),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),

                # Borders
                ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                ("BOX", (0, 0), (-1, -1), 1, colors.black),
            ]
        )
    )

    stats_table.hAlign = "CENTER"

    return stats_table


# Build the complete PDF content.
def _build_pdf_content(
    history: list[ChatMessage],
    styles,
    metadata_table: Table,
    stats_table: Table,
) -> list:
    """
    Build the complete PDF content.

    Returns:
        List of ReportLab Flowables.
    """

    conversation = _build_conversation(
        history,
        styles,
    )   

    content = [

        # Title

        Paragraph(
            "Memory ChatBot AI",
            styles["Title"],
        ),

        Paragraph(
            "Conversation Export Report",
            styles["Heading2"],
        ),

        Spacer(1, 20),


        # Metadata

        metadata_table,

        Spacer(1, 20),


        # Statistics

        Paragraph(
            "Conversation Statistics",
            styles["Heading2"],
        ),

        Spacer(1, 12),

        stats_table,

        Spacer(1, 24),


        # Conversation

        *conversation,

        Spacer(1, 24),


        # Footer

        HRFlowable(
            width="100%",
            thickness=1,
            color=colors.grey,
        ),

        Spacer(1, 12),

        Paragraph(
            f"Generated by <b>Memory ChatBot AI v{APP_VERSION}</b>",
            styles["Normal"],
        ),

        Paragraph(
            f"Built by <b>{AUTHOR}</b>",
            styles["Normal"],
        ),
    ]

    return content


# Build the conversation section of the PDF.
def _build_conversation(
    history: list[ChatMessage],
    styles,
) -> list:
    """
    Build the conversation section of the PDF.

    Returns:
        List of ReportLab Flowables.
    """

    conversation = [
        Paragraph(
            "Conversation",
            styles["Heading2"],
        ),
        Spacer(1, 12),
    ]

    for message in history:

        speaker = (
            "User"
            if message["role"] == "user"
            else "Assistant"
        )

        conversation.append(
            Paragraph(
                f"<b>{speaker}</b>",
                styles["Heading3"],
            )
        )

        conversation.append(
            Spacer(1, 10)
        )

        conversation.append(
            Paragraph(
                f"<font color='grey'>{message['timestamp']}</font>",
                styles["Normal"],
            )
        )

        conversation.append(
            Spacer(1, 8)
        )

        conversation.append(
            Paragraph(
                message["content"],
                styles["BodyText"],
            )
        )

        conversation.append(
            Spacer(1, 16)
        )

        conversation.append(
        HRFlowable(
            width="100%",
            thickness=0.5,
            color=colors.lightgrey,
        )
    )

    conversation.append(
        Spacer(1, 12)
    )

    return conversation

def export_as_pdf(
        history: list[ChatMessage],
        metadata: ConversationMetadata,
) -> bytes:
    """
    Generate a simple PDF and return it as bytes.
    """
    # Create a BytesIO buffer to hold the PDF data

    buffer = BytesIO()

    # Create a SimpleDocTemplate with the buffer as the file-like object

    document = SimpleDocTemplate(
        buffer,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40,
        )

    # Get chat statistics from the conversation history

    stats: ChatStatistics = get_chat_statistics(history)

# Create a table for conversation metadata

    metadata_table = _create_metadata_table(metadata)

# Create a table to display the statistics in the PDF

    stats_table = _create_statistics_table(stats)

# Create a list to hold the flowable elements (content) of the PDF

    styles = getSampleStyleSheet()

    content = _build_pdf_content(
        history,
        styles,
        metadata_table,
        stats_table,
    )

#  this tell Reportlab Take all these elements and generate the PDF.
    document.build(content)

    buffer.seek(0)

    return buffer.getvalue()

